/**
 * knip — dead code & unused export detector
 * --------------------------------------------------------------------------
 * Used by `npm run audit:dead`. See `.claude/methodology/05-DEAD-CODE-AUDIT.md`.
 *
 * Entry points: anything that bootstraps execution (browser, edge runtime,
 * test runner, config tooling). From these, knip walks the import graph to
 * find unreachable files / unused exports.
 */
import type { KnipConfig } from "knip";

const config: KnipConfig = {
  entry: [
    "src/main.tsx",
    "src/App.tsx",
    "supabase/functions/*/index.ts",
    "tests/**/*.spec.ts",
    "vite.config.ts",
    "tailwind.config.ts",
    "playwright.config.ts",
    "postcss.config.js",
    "eslint.config.js",
  ],
  project: ["src/**/*.{ts,tsx}", "supabase/functions/**/*.ts"],
  ignore: [
    // Auto-generated by Supabase/Lovable — periodically regenerated, do not flag
    "src/integrations/supabase/types.ts",
    // shadcn/ui primitives — kept available even if currently unused (future Stitch
    // implementations may pull in a Drawer, Menubar, etc.)
    "src/components/ui/**",
  ],
  ignoreDependencies: [
    // Used implicitly via lint-staged config in package.json
    "husky",
    "lint-staged",
    "prettier",
    // Used only via npm scripts / tooling, not import graph
    "@playwright/test",
  ],
  ignoreBinaries: [
    // Some scripts call binaries that knip can't always trace
    "tsc",
  ],
};

export default config;
